scope: postgres-cluster
namespace: /db/
name: patroni-1
restapi:
  listen: 192.168.139.129:8008
  connect_address: 192.168.139.129:8008
etcd:
  hosts: 192.168.139.129:2379,192.168.139.142:2379,192.168.139.90:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        autovacuum_analyze_scale_factor: 0.01

  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 127.0.0.1/8 md5
    - host replication replicator 192.168.139.129/32 scram-sha-256
    - host replication replicator 192.168.139.142/32 scram-sha-256
    - host replication replicator 192.168.139.90/32 scram-sha-256
    - host all all 0.0.0.0/0 scram-sha-256

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1,192.168.139.129:5432
  connect_address: 192.168.139.129:5432
  data_dir: /var/lib/postgresql/17/main
  bin_dir: /usr/lib/postgresql/17/bin
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: replicator
      password: replicator
    rewind:
      username: rewind_user
      password: rewind_user
  parameters:
    unix_socket_directories: '.'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
